_BASE_: [
  '_base_/mot17.yml',
  '../runtime.yml',
  '../ppyoloe/_base_/optimizer_40e.yml',
  '../ppyoloe/_base_/ppyoloe_plus_crn.yml',
  '../ppyoloe/_base_/ppyoloe_plus_reader.yml',
]
log_iter: 100
snapshot_epoch: 2
weights: output/ppyoloe_plus_sod_crn_l_80e_coco/model_final

pretrain_weights: https://bj.bcebos.com/v1/paddledet/models/pretrained/ppyoloe_crn_l_obj365_pretrained.pdparams
depth_mult: 1.0
width_mult: 1.0

architecture: ByteTrack
ByteTrack:
  detector: YOLOv3 # PPYOLOe version
  reid: None
  tracker: JDETracker
det_weights: output/best_model/model.pdparams
reid_weights: None

CustomCSPPAN:
  num_layers: 4
  use_trans: True


PPYOLOEHead:
  reg_range: [-2, 17]
  static_assigner_epoch: -1
  assigner:
    name: TaskAlignedAssigner_CR
    center_radius: 1
  nms:
    name: MultiClassNMS
    nms_top_k: 1000
    keep_top_k: 300
    score_threshold: 0.01
    nms_threshold: 0.3

# BYTETracker
JDETracker:
  use_byte: True
  match_thres: 0.5
  det_thresh: 0.25
  conf_thres: 0.25
  tracked_thresh: 0.25
  low_conf_thres: 0.10
  min_box_area: 50
#  vertical_ratio: 1.6 # for pedestrian
  vertical_ratio: -1 # for pedestrian
  track_buffer: 100