metric: COCO
num_classes: 1

TrainDataset:
  name: COCODataSet
  image_dir: train
  anno_path: annotations/train.json
  dataset_dir: dataset/standford_campus
  data_fields: ['image', 'gt_bbox', 'gt_class', 'is_crowd']

EvalDataset:
  name: COCODataSet
  image_dir: val
  anno_path: annotations/val.json
  dataset_dir: dataset/standford_campus
  allow_empty: true

TestDataset:
  name: ImageFolder
  anno_path: annotations/val.json # also support txt (like VOC's label_list.txt)
  dataset_dir: dataset/standford_campus # if set, anno_path will be 'dataset_dir/anno_path'